version: '3.1'
services:
  mongo:
    image: mongo:4.4.5
    restart: always
    ports:
      - 9003:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - ../container/mongo/data:/data